# Generated by Django 3.1.5 on 2022-03-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjacencyMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_graph', to='graph.graphs')),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.graphs')),
            ],
        ),
        migrations.DeleteModel(
            name='ParentGraph',
        ),
    ]
