# Generated by Django 3.1.5 on 2022-03-08 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_operation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResultGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graph.graphs')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.operations')),
            ],
        ),
    ]
